In [ ]:
# W tym notatniku znajdują się fundamentalne koncepty używając tensorflow
# Wstęp do tensorów
# Zbieranie onformacji z tensorów
# manipulowanie tensorami
# Tensory i NumPy
# Używanie @tf.fucntion aby przyspieszyć funkcje pythona
# Używanie GPU z Tensorflow

In [ ]:
# Wstęp do TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
# Stworzenie tensorów z tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Sprawdź ilość wymiarów tensora(ndim to liczba wymiarów)
scalar.ndim

0

In [ ]:
# Stwórz vektor
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Sprawdź ilość wymiarów vektora
vector.ndim

1

In [ ]:
# Stwórz macierz (ma więcej niż 1 wymiar)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Sprawdź ilość wymiarów macierzy
matrix.ndim

2

In [ ]:
# Stwórz inną macierz
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8., 9.]], dtype=tf.float16) # określ typ danych parametrem dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Sprawdź ilość wymiarów innej macierzy
another_matrix.ndim

2

In [ ]:
# Stwórz tensor
tensor = tf.constant([[[1, 2, 3], 
                       [4, 5, 6]], 
                      [[7, 8, 9], 
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# Sprawdź ilość wymiarów tensora
tensor.ndim

3

In [ ]:
# Co do tej pory stworzyliśmy
# Scalar: cyfra pojedyńcza
# Vector: cyfra z kierunkiem
# Matrix: 2 wymiarowa macierz cyfr
# Tensor: n-wymiarowa macierz cyfr (gdzie n może być dowolną cyfrą, gdzie 0-wymiarowy tensor to scalar, a 1-wymiarowy tensor to vector)
#


In [ ]:
### Tworzenie tensorów tf.Variable

In [ ]:
# Stórz ten samo tensor z tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Zmień jeden element w changeable_tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# Spróbojemy użyć .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Zmień jeden element w unchangeable_tensor
unchangeable_tensor[0].assign(7)
unchangrable_tensor

AttributeError: ignored

In [ ]:
### Tworzenie losowych tensorów
# Losowy tensor to tensor o arbitralnej wielkości wypełniony cyframi

In [ ]:
# Stwórz dwa losowe (takie same) tensory
random_1 = tf.random.Generator.from_seed(7) # ustaw ziarno do reprodukcji
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# czy są takie same?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
### Przetasuj elementy w tensorze (należy sortować dane jeśli ich kolejność może mieć wpływ na wyniki)
not_shuffled = tf.constant([[10, 7], 
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim
# Przetasuj not_suffled
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
## **Exercise:** Read trought TensorFlow documentation on random seed generation

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
### Inne sposoby tworzenia tensorów

In [ ]:
# Stwórz tensor jedynek
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Stwórz tensor zer
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
### Przerób macierze NumPy na tensory
# Główna różnica między macierzami NumPy i Tensor Flow jest taka, że tensory mogą wykorzystywać GPU do przeprowadzania obliczeń

In [ ]:
# Możesz zmienić macierze NumPy w tensory
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # stwórz macierz numpy pomiędzy 1 i 25
numpy_A

# x = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
### Uzyskiwanie informacji z tensorów
# Pracując z tensorami trzeba być swiadomym ich atrybutów 
# Shape - długość(liczba elementów każdego wymiaru tensora) - tensor.shape
# Rank - liczba wymiarów (scalar ma rank 0, vector ma rank 1, matrix ma rank 2, tensor ma rank n) tensor.ndim
# Axis of dimension - wybrany wymiar tensora - tensor[0], tensor[:, 1]...
# Size - łączna ilość przedmiotów w tensorze - tf.size(tensor)

In [ ]:
# Stwórz tensor rank 4
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Zbierz poszczególne atrybuty tensora
print("Typ danych każdego elementu: ", rank_4_tensor.dtype)
print("Ilość wybiarów(rank): ", rank_4_tensor.ndim)
print("Krztałt tensora: ", rank_4_tensor.shape)
print("Elementy osi 0: ", rank_4_tensor.shape[0])
print("Elementy ostatniej osi: ", rank_4_tensor.shape[-1])
print("Łączna ilość elementów w tensorze: ", tf.size(rank_4_tensor))
print("Łączna ilość elementów w tensorze: ", tf.size(rank_4_tensor).numpy())

Typ danych każdego elementu:  <dtype: 'float32'>
Ilość wybiarów(rank):  4
Krztałt tensora:  (2, 3, 4, 5)
Elementy osi 0:  2
Elementy ostatniej osi:  5
Łączna ilość elementów w tensorze:  tf.Tensor(120, shape=(), dtype=int32)
Łączna ilość elementów w tensorze:  120


In [ ]:
### Indexowanie tensorów
# tensory mogą być indeksowane jak pythonowe listy

In [ ]:
# Uzyskaj pierwsze 2 elementy z każdego wymiaru tensora
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [ ]:
# Uzyskaj pierwszy element z każdego wymiaru dla każdego indeksu za wyjątkiem ostatniego
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Stwórz tensor rank 2
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [ ]:
# Weź ostatni przedmiot każdego rzędu z 2 wymiarowego tensora
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Dodaj dodatkowy wymiar do tensora rank 2
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
#rank_3_tensor = rank_2_tensor[:,:, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternatywa dla tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 oznacza ostatnią oś

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Dodaj wymiar 0
tf.expand_dims(rank_2_tensor, axis=0) # 0 oznacza pierwszą oś

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
### Manipulowanie tensorami (tensor operations)
# Podstawowe operacje

In [ ]:
# Możesz dodawać wartości do tensora używając operatora dodawania
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Originalny tensor jest niezmieniony
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Mnożenie także działa
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tensor / 10 

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
# Możemy użyć funkcji wbudowanych w TensorFlow
tf.multiply(tensor, 10)
tf.add(tensor, 10)
tf.subtract(tensor, 10)
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
## Mnożenie macierzy
# Jedna z najczęściej występujących operacji w TensorFlow

In [ ]:
# Mnożenie macierzy w TensorFlow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Mnożenie macierzy w pythonie
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Stwórz tensor (3, 2)
X = tf.constant([[1,2],
                 [3, 4],
                 [5, 6]])
# Stwórz kolejny tensor
Y = tf.constant([[7, 8], 
                 [9, 10], 
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Spróbuj pomnożyć tensory tego samego kształtu
tf.matmul(X, Y)
# Są dwie zasady jakie muszą przestrzegać macierze/tensory przy mnożeniu
# 1. wewnętrzne wymiary muszą się zgadzać
# 2. macież końcowa musi mieć kształt zewnętrznych wymiarów

InvalidArgumentError: ignored

In [ ]:
# Zmieńmy kształt Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Spróbuj pomnożyć X przez zmienione Y
x@ tf.reshape(Y, shape=(2, 3))

NameError: ignored

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(X, shape=(2, 3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Możemy tak samo transponować macierze
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Spróbuj pomnożyć macierze transpozycją, a nie reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Mnożenie macierzy jest zwane także jako dot product
# Możesz mnożyć macierze za pomocą
# tf.matmul()
# tf.tensordot()

In [ ]:
# Wykonaj dot product na X u Y (wymaga X lub Y do transpozycji)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Wykonaj mnożenie macierzy pomiędzy X i Y (transpozycja)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Wykonaj mnożenie macierzy pomiędzy X i Y (reshape)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Sprawdź wartość Y, reshaped Y i transponowanego Y
print("normalne Y: \n", Y)
print("Y reshaped: \n", tf.reshape(Y, (2, 3)))
print("Y transposed: \n", tf.transpose(Y))

normalne Y: 
 tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Y reshaped: 
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Y transposed: 
 tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
# Prawidłowe mnożenie macierzy przebiega
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
### Zmiana typu danych tensora

In [ ]:
# Stwórz nowy tensor z wartością float32
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C=tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# Zmień z float32 do float16 (reduced precision)
D= tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Zmień z int32 do float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [ ]:
E_float_16 = tf.cast(E, dtype=tf.float16, ) 
E_float_16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [ ]:
# Agregowanie tensorów - kondensowani ich z wielu wartości w dół do mniejszej ilości wartości.

In [ ]:
# Weź absolutne wartości
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Przejdziemy przez następujące formy agregacji:
# weźmiemy minimum
# weźmiemy maximum
# weźmiemy mediane tensora
# weźmiemy sumę tensora

In [ ]:
# Stwórz losowy tensor z wartościami pomiędzy 0 i 100 z wielkością 50
E = tf.constant(np.random.randint(0, 100, size=100))
E

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([79, 65, 55,  9, 36, 99, 13, 45, 12, 39, 88, 23, 97,  4, 71, 80,  6,
       47, 94, 24, 77, 49, 79, 52, 32,  2,  4, 20, 94, 27, 47, 36, 95, 33,
       23, 73, 88, 98, 98, 75, 78, 17, 59, 44, 81, 84, 83,  0, 48, 91, 31,
       41, 64, 16, 32, 31, 83, 32, 93, 42,  5, 25, 32, 90, 25, 51, 17, 67,
       45, 95, 18, 47, 88, 21, 39, 28, 95, 70, 22, 86, 24, 45, 25,  7, 31,
       66, 30, 91, 12,  6, 19, 22, 57, 39, 30, 11, 85, 16, 57, 39])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=100>, TensorShape([100]), 1)

In [ ]:
# Znajdź minimum tensora
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Znajdź maximum tensora
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Znajdź mediane tensora
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
# Znajdź sumę tensora
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4816>

In [ ]:
## Zadanie, w oparciu o to czego się nauczyłeś znajdź variancję i odchylenie standardowe tensora E używając metod tensorflow

In [ ]:
# Znajdź variancję tensora
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=884>

In [ ]:
# Znajdź wariancję tensora
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=884.0544>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.733051>

In [ ]:
### Znajdź pozycje maximum i minimum tensora

In [ ]:
# Stwórz nowy tensor aby znaleźć pozycyjne minimum i maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Znajdź pozycje maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Zindexuj naszą największą wartość pozycji
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Znajdżź maxymalną wartość F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Sprawdź równość
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Zindexuj najmniejszą wartość pozycji
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Znajdź minimalną używaną wartość F
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
### Wyciskanie tensora (Usuwanie pojedyńczych wymiarów)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

In [ ]:
### One-hot encoding tensors

In [ ]:
# Stwórz listę indices
some_list = [0, 1, 2, 3] # could be red, green, blue
# One hot encode naszą listę indicies
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Usaw customowe wartości dla one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [ ]:
### Squaring, log, square root

In [ ]:
# Stwórz nowy tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it(potęguj to)
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Znajdź square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# Znajdź logarytm
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
### Tensory i NumPy
# Tensorflow ma idealne interakcje z macierzami NumPy

In [ ]:
#Stwórz tensor bezpośrednio z macierzy Numpy
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# Defaultowe typy są odrobine inne
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
#sprawdź typy każdego
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)